### ISSUE TITLE
A release compatible with Quarkus 3

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/quarkus-freemarker#161]
I see that the necessary changes are merged in `master` branch. Could we please get a release compatible with the recent Quarkus 3.0.0.Alpha3, so that we can test in Camel Quarkus?

**Comment by vsevel** [comment]
see https://github.com/quarkiverse/quarkus-freemarker/pull/162

**Comment by vsevel** [comment]
the build for the PR passed
but the release failed anyhow:
```
Switched to branch 'master'
M	deployment/src/main/java/io/quarkiverse/freemarker/deployment/FreemarkerProcessor.java
M	integration-tests/config-defaults/src/main/java/io/quarkiverse/it/freemarker/ConfigDefaultsResource.java
M	integration-tests/legacy-config/src/main/java/io/quarkiverse/it/freemarker/FreemarkerTestResource.java
M	integration-tests/template-sets/src/main/java/io/quarkiverse/it/freemarker/TemplateSetsResource.java
M	runtime/src/main/java/io/quarkiverse/freemarker/runtime/FreemarkerConfigurationProducer.java
M	runtime/src/main/java/io/quarkiverse/freemarker/runtime/FreemarkerTemplateProducer.java
Your branch is up to date with 'origin/master'.
error: cannot rebase: You have unstaged changes.
error: Please commit or stash them.
Error: Process completed with exit code 1.
```
any idea @gastaldi ?

**Comment by gastaldi** [comment]
@vsevel you have formatting issues in the code (probably caused when https://github.com/quarkiverse/quarkus-freemarker/commit/6d8274534b6fbf1803613f71013b5e23fc3b6a85 was merged). 

I'll send a PR fixing the workflow scripts to prevent that from happening again

**Comment by gastaldi** [comment]
@vsevel fix in https://github.com/quarkiverse/quarkus-freemarker/pull/163

**Comment by vsevel** [comment]
trying the release again from https://github.com/quarkiverse/quarkus-freemarker/pull/164

**Comment by vsevel** [comment]
one more try https://github.com/quarkiverse/quarkus-freemarker/pull/166

**Comment by ppalaga** [comment]
Thanks @vsevel, I can see 1.0.0.Alpha1 in Central and I was able to test with it successfully.
