### ISSUE TITLE
Correct dependency definition

### ISSUE THREAD

**Issue by k-wilmeth** [quarkiverse/quarkus-freemarker#175]
Hello, I am attempting to add this extension in my pom.xml but am getting the 'Could not find artifact' whenever I try. What is the most recent version that has been deployed or am I just not correctly filling out the extension info? I have had no problem importing other _quarkiverse_ extensions, except this one.

According to your [documentation](https://quarkiverse.github.io/quarkiverse-docs/quarkus-freemarker/dev/index.html), this is how we should be importing the extension:
```
<dependency>
    <groupId>io.quarkiverse</groupId>
    <artifactId>quarkiverse-freemarker</artifactId>
    <version>{project-version}</version>
</dependency>
```

However, on Github it is listed as another way,
```
<dependency>
    <groupId>io.quarkiverse.freemarker</groupId>
    <artifactId>quarkus-freemarker</artifactId>
</dependency>
```

Can you please direct me as to how I can import the extension into my project correctly? Some updated documentation might be great as well. Thank you for the time.

**Comment by k-wilmeth** [comment]
False alarm. I found the most recent version(1.0.0.Alpha1) in the Releases section.

**Comment by vsevel** [comment]
`Alpha.2` has been released yesterday FYI
